import Link from "next/link";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex justify-between items-center gap-5">
          <h1>NEXT AUTH</h1>
          <div className="flex gap-5">
            <Link href="/">Home</Link>
            <Link href="/register">Register</Link>
            <Link href="/login">Login</Link>
            <Link href="/profile">Profile</Link>
            <Link href="/profile">Profile</Link>
          </div>
        </div>
        {children}
      </body>
      <div>
        <h1>Footer</h1>
      </div>
    </html>
  );
}
